site_name: "Programação Web 2 - Uma abordagem usando Node/Express"
site_description: "Material do Curso de Programação Web 2 do curso de Bacharelado em Desenvolvimento de Sistemas do IFAL-Maceió"
site_url: "https://leofernandesmo.github.io/pweb2-book/"
repo_url: "https://github.com/leofernandesmo/pweb2-book/"
repo_name: "GitHub"

theme:
  name: material
  language: pt
  features:
    - navigation.tabs
    - navigation.top
    - navigation.sections
    - navigation.indexes
    - content.code.copy
    - content.action.edit
    - content.action.view
    - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

extra:
  social:
    - icon: fontawesome/brands/github
      link: "https://github.com/leofernandesmo"

markdown_extensions:
  - admonition
  - footnotes
  - toc:
      permalink: true
  - codehilite:
      guess_lang: false
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.emoji
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - search
  - print-site:
      add_to_navigation: true
      print_page_title: "Print / Save PDF"  


extra_javascript:
  - assets/js/quiz.js
  - assets/js/code-runner.js

extra_css:
  - assets/extra.css
  - assets/css/custom.css

nav:
  - Home: index.md
  - Cover: cover.md
  - Title Page: title-page.md
  - Preface: preface.md
  - Chapters:
      - "0. Como User Este Material": chapters/00-how-to-use.md
      - "1. Introdução a Programação Web": chapters/01-introducao.md
      - "Appendix": chapters/99-appendix.md      
  - Back Cover: back-cover.md

